addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.4.6")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"   % "0.10.2")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.10")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"       % "2.3.3")
addSbtPlugin("com.github.sbt" % "sbt-unidoc"     % "0.5.0")
