addSbtPlugin("org.scalameta"  % "sbt-scalafmt"   % "2.5.2")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"   % "0.12.1")
addSbtPlugin("com.github.sbt" % "sbt-ci-release" % "1.5.12")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"       % "2.5.3")
addSbtPlugin("com.github.sbt" % "sbt-unidoc"     % "0.5.0")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"  % "0.12.0")
