name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.2
      - name: Setup Java
        uses: actions/setup-java@v3.1.1
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Cache scala dependencies
        uses: coursier/cache-action@v6
      - name: Check code formatting
        run: sbt check

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        scala: ['2.12.15', '2.13.8']
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.2
      - name: Setup Java
        uses: actions/setup-java@v3.1.1
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Cache Scala dependencies
        uses: coursier/cache-action@v6
      - name: Run tests
        run: sbt ++${{ matrix.scala }}! test

  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies and build website
        working-directory: ./website
        run: yarn install --frozen-lockfile && yarn build

  ci:
    runs-on: ubuntu-latest
    needs: [lint, test, test-deploy]
    steps:
      - name: Aggregate outcomes
        run: echo "build succeeded"
