name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.0.2
      - name: Setup Java
        uses: actions/setup-java@v3.1.1
        with:
          distribution: temurin
          java-version: 17
          check-latest: true
      - name: Cache Scala dependencies
        uses: coursier/cache-action@v6
      - name: Generate website
        run: sbt docs/docusaurusCreateSite
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./website/build
